### PR TITLE
#17:  List all taxes

### PR DESCRIPTION
**Pull request by BeeMargarida**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-invoicing/issues/17 |
| Dependencies | -- |
| Decisions | - Method to list all taxes - this will be necessary to get the tax that must be used to calculate the unit price from the total price for invoice creation<br>- Bumped packages |
| Animated GIF | -- |

### CODE REVIEW

**Review by 3rdvision — APPROVED** [review]

**Review by joao-conde — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Comment by joamag** [comment]
@BeeMargarida we need to figure out how can we cover this with tests

**Comment by BeeMargarida** [comment]
> @BeeMargarida we need to figure out how can we cover this with tests

The tests are on peri invoicing side, I think we don't normally test apis

**Comment by joamag** [comment]
> 

True, but we need to start doing that. Just to increase our trust levels on the API clients.
Overall our goal is to go with 100% test coverage in every single project.

**Comment by joamag** [comment]
Obviously we're not reaching that goals in the near future. But we must start a strategy to reach it.

**Comment by BeeMargarida** [comment]
> .
> Overall our goal is to go with 100% test coverage in every single project.

Testing this API client, for example, we would basically be testing their API or using mocks to replicate their responses. Is this what is expected?

**Pull request merged**
